# -*- coding: utf-8 -*-
"""Patterns[18th May 2022].ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SErsVdl-Gp7GVb-FBZdnu9GusieXZ01w
"""

s=int(input("What size base do you want?:-  "))
for e in range(0,s):
  for f in range(0,e+1):
     print("*",end=" ")
  print("\r")

s=int(input("What size base do you want?:-  "))
x=2*s-2
for e in range(0,s):
  for f in range(0,x):
    print(end=" ")
  x=x-2
  for f in range(0,e+1):
    print(" ",end="*")
  print(" ")

s=int(input("What size base do you want?:-  "))
x=s-1
for e in range(0,s):
  for f in range(0,x):
    print(end=" ")
  x=x-1
  for f in range(0,e+1):
    print("*",end=" ")
  print("\r")

s=int(input("What size base do you want?:-  "))
x=s-1
for e in range(0,s):
  for f in range(0,x):
    print(end=" ")
  x=x-1
  for f in range(0,e+1):
    print("*",end=" ")
  print("\r")

x = '*' 
q= int(input('number or rows for the triangle: '))
triangle =[q*x+" ",(q-1)*x+" ",(q-2)*x+" ",(q-3)*x+" ",(q-4)*x+" ",(q-5)*x+" ",(q-6)*x+" ",(q-7)*x+" ",(q-8)*x+" ",(q-9)*x+" "]
if q>10:
  print("Triangle size not suported")
elif q<=10 and q>=2:
  for y in triangle:
    print(y)
else:
  print("A triangle should have atleast 3 points")